## Homework.4 31-A.Utilizing Numpy Function

In [1]:
import numpy as np
import numpy.linalg as NL

## 1.Create an array of size 10 filled with 0

In [2]:
a = np.zeros(10, float)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 2.Set fifth value to 1 from above array

In [3]:
a = np.zeros(10, float)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 3.Create an array with values ranging from 10 to 49

In [4]:
a = np.arange(10,50,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4.Create a 5*5 matrix with values ranging from 0 to 24

In [5]:
a = np.arange(0,25,1).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 5.Create a 5*5 identity matrix

In [6]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 6.Create an 5*5 array with random values and find the minimum and maximum value

In [7]:
a = np.random.random((5,5))
print('Minimum value : ', a.min(), ' Maximum value : ', a.max())

Minimum value :  0.001521145143633218  Maximum value :  0.9752497204772331


## 7.Multiply a 4*3 matrix by a 3*2 matrix
### 4*3 matrix is filled with 1
### 3*2 matrix is filled with random number

In [8]:
a = np.full((4,3),1)
b = np.random.randint(10, size=(3,2))
m = np.dot(a,b)
m

array([[13, 20],
       [13, 20],
       [13, 20],
       [13, 20]])

## 8.Transpose the above matrix

In [9]:
mt = m.transpose()
mt

array([[13, 13, 13, 13],
       [20, 20, 20, 20]])

## 9.Create two matrices ranging from 0 to 24 and 25 to 49

In [10]:
a = np.arange(0,25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
b = np.arange(25,50).reshape((5,5))
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

## Add to matrix

In [12]:
m_add = a+b
m_add

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

## Substract two matrix

In [13]:
m_sub = a-b
m_sub

array([[-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25],
       [-25, -25, -25, -25, -25]])

## Q1.다음 코드의 실행 결과의 형태를 예측하시오

In [14]:
a1_1 = np.array([[1,2],[3,4]])
a1_2 = np.array([[1,2],[3,4],[5,6]])

NL.eig(a1_1)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

#### → a1_1 matrix의 eigen value array와 eigen vector array가 반환된다

In [15]:
NL.eig(a1_2)

LinAlgError: Last 2 dimensions of the array must be square

#### →Square Matrix가 아니므로 eigenvalue, eigenvector 계산시 오류 발생

In [16]:
NL.svd(a1_1, full_matrices=True)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

#### → a1_1 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=True 이므로 Full SVD 결과를 반환한다

In [23]:
NL.svd(a1_1, full_matrices=False)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

#### → a1_1 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=False 이므로 Reduce SVD 결과를 반환한다

In [18]:
NL.svd(a1_2, full_matrices=True)

(array([[-0.2298477 ,  0.88346102,  0.40824829],
        [-0.52474482,  0.24078249, -0.81649658],
        [-0.81964194, -0.40189603,  0.40824829]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

#### → a1_2 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=True 이므로 Full SVD 결과를 반환한다

In [19]:
NL.svd(a1_2, full_matrices=False)

(array([[-0.2298477 ,  0.88346102],
        [-0.52474482,  0.24078249],
        [-0.81964194, -0.40189603]]),
 array([9.52551809, 0.51430058]),
 array([[-0.61962948, -0.78489445],
        [-0.78489445,  0.61962948]]))

#### → a1_2 Matrix의 Singular Value Decomposition 결과인 U,S,V Matrix를 반환한다.
####  full_matrrices=False 이므로 Reduce SVD 결과를 반환한다

##  Q2. 주어진 코드와 실행 결과가 다음과 같을 때, 결과 값 x,y의 의미와 그 관계에 대해 설명하시오.

In [21]:
a2 = np.array([[7,1],[1,7]])
x,y = NL.eig(a2)
x,y

(array([8., 6.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

#### → x = a2 matrix의 eigen value
#### → y = a2 matrix의 eigen vector

## Q3. 주어진 코드의 실행 결과인 U, S, V의 형태를 예측하고, 각 결과 값이 의미하는 바를 쓰시오.

In [22]:
a3 = np.array([[1,1,1,0,0,],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])
U,S,V = NL.svd(a3, full_matrices=False)
U,S,V

(array([[-1.37599126e-01,  2.36114514e-02,  1.08084718e-02,
          9.90147543e-01, -1.26568534e-16],
        [-4.12797378e-01,  7.08343543e-02,  3.24254153e-02,
         -5.94088526e-02, -8.85034377e-01],
        [-5.50396503e-01,  9.44458057e-02,  4.32338870e-02,
         -7.92118034e-02,  4.24264069e-01],
        [-6.87995629e-01,  1.18057257e-01,  5.40423588e-02,
         -9.90147543e-02,  1.91609371e-01],
        [-1.52775087e-01, -5.91100963e-01, -6.53650843e-01,
         -9.73880310e-17,  4.77815907e-17],
        [-7.22165140e-02, -7.31311857e-01,  6.78209218e-01,
          4.93038066e-32, -7.10764783e-17],
        [-7.63875433e-02, -2.95550482e-01, -3.26825421e-01,
         -4.86940155e-17, -3.16203559e-17]]),
 array([1.24810147e+01, 9.50861406e+00, 1.34555971e+00, 1.84716760e-16,
        9.74452038e-33]),
 array([[-5.62258405e-01, -5.92859901e-01, -5.62258405e-01,
         -9.01335372e-02, -9.01335372e-02],
        [ 1.26641382e-01, -2.87705846e-02,  1.26641382e-01,
        

#### full_matrices = False 이므로 reduce SVD  결과를 반환한다
#### U : a3를 고유값 분해하여 얻어진 orthogonal matrix (Left singular vector)  - 5x7 matrix
#### S : a3를 고유값 분해하여 얻어진 eigen value array (singular value) - 5개
#### V : a3를 고유값 분해하여 얻어진 orthogonal matrix (Right singular vector) - 5x5 matrix